rm(list=ls())
## install and load libraries for all analyses
install.packages("vegan")
install.packages("piecewiseSEM")
install.packages("lme4")
install.packages("lmerTest")
install.packages("tidyverse")
library(vegan)
library(piecewiseSEM)
library(lme4)
library(lmerTest)
library(tidyverse)
